num1 = int(input("Enter a number: "))
num2 = int(input("Enter another number: "))
print("The sum of the numbers is: ", num1+num2)
print("The difference of the numbers is: ", num1-num2)
print("The product of the numbers is: ", num1*num2)
print("The decimal quotient of the numbers is: ", num1/num2)
print("The integer quotient of the numbers is: ", num1//num2)
print("The exponent of the numbers is: ", num1**num2)
print("The remainder of the numbers is: ", num1%num2)
